site_name: Rakhshai GNN
nav:
  - Home: index.md
  - Persian Tokenizer: persian_tokenizer.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [rakhshai_graph_nlp]
