name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install project (with extras)
        run: pip install -e ".[sparse,ml,fa,docs]"

      - name: Install tooling
        run: pip install ruff mypy pytest

      - name: Ruff (lint)
        run: ruff check . --output-format=github

      - name: Mypy (types)
        run: mypy rakhshai_graph_nlp

      - name: Pytest
        run: pytest -q
